ding:
  description: 发送消息到钉钉机器人。
  fields:
    message:
      description: 消息内容。
      example: '您好，我是钉钉机器人'

miai:
  description: 用小爱音箱播报消息。
  fields:
    message:
      description: 消息内容
      example: '您好，我是小爱'
    volume:
      description: 指定音量（可选，默认不改变音量；指定音量时消息内容可以为空）
      example: '50'
    devno:
      description: 指定音箱序号（可选，默认为 0）
      example: '0'
